### ISSUE TITLE
[硬件安装]修改建议汇总

### ISSUE THREAD

**Issue by WuLyon** [pixmoving-moveit/pixkit-documentation-cn#24]
# 版本
https://github.com/pixmoving-moveit/pixkit-documentation-cn/commit/94e85d239a99e908565fc0ddec1c64757e2dd3ff

# 问题描述

## 一、IPC安装
![图片](https://user-images.githubusercontent.com/61351119/237054612-7c528ad9-cbe8-4618-9428-5ffb8e45162a.png)
![图片](https://user-images.githubusercontent.com/61351119/237054895-87c2e4d9-b49d-46e0-b35c-2f2607f9c9d0.png)
![图片](https://user-images.githubusercontent.com/61351119/237055150-e4574276-21e5-4a62-9823-311f3131163f.png)
![图片](https://user-images.githubusercontent.com/61351119/237055269-c9a46722-5031-4003-ab3d-06c7ad0a4fdd.png)
![图片](https://user-images.githubusercontent.com/61351119/237055401-1402f0f8-c1ef-4e6a-8bbf-01edf68de314.png)

## 二、LiDAR安装
![图片](https://user-images.githubusercontent.com/61351119/237056704-6cc348f3-e30a-40d3-b114-f7ca9be6f056.png)
![图片](https://user-images.githubusercontent.com/61351119/237057061-8a49e22e-2ade-44f6-8e4b-43f27844287c.png)

![图片](https://user-images.githubusercontent.com/61351119/237057786-8a54e441-c5dd-47fe-9187-f87b33ef853d.png)
![Screenshot from 2023-05-09 17-05-01](https://user-images.githubusercontent.com/61351119/237057928-5d2baf14-c049-4818-9eca-50047f81c74b.png)

## 三、camera安装
![图片](https://user-images.githubusercontent.com/61351119/237058629-0900612c-46d9-4cf6-8d7e-52937d96cb84.png)
![图片](https://user-images.githubusercontent.com/61351119/237058667-2881a379-26a7-4564-82a3-b8d8f75aa3dd.png)

## 四、GNSS安装
![图片](https://user-images.githubusercontent.com/61351119/237059046-23e6f9ff-f7c7-4ee1-b3ff-bfcfd09b5cb3.png)
![图片](https://user-images.githubusercontent.com/61351119/237059179-f7cea361-7038-45dc-a6ec-9bf25a28a9f9.png)

![图片](https://user-images.githubusercontent.com/61351119/237059391-6366f2a7-162c-43a7-91db-00329b816683.png)
![图片](https://user-images.githubusercontent.com/61351119/237059701-08a120f4-3db0-4354-9192-c940dbf55b8c.png)
![图片](https://user-images.githubusercontent.com/61351119/237059932-05ec1619-34c0-4c1d-b479-5b7dca93deca.png)

**Comment by ahuazuipiaoliang** [comment]
@pixwyh 益辉请看一下

**Comment by pixwyh** [comment]
收到，我这边修改完成之后会关闭这个issues

**Comment by pixwyh** [comment]
已经修改，感谢力洋细心的查看，和合理的建议
