### ISSUE TITLE
[传感器标定]修改汇总

### ISSUE THREAD

**Issue by WuLyon** [pixmoving-moveit/pixkit-documentation-cn#25]
# 版本
https://github.com/pixmoving-moveit/pixkit-documentation-cn/commit/94e85d239a99e908565fc0ddec1c64757e2dd3ff
# 问题描述
## 一、标定工具集合安装
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/fe7b88d3-35a2-4ea6-9812-2c45ab9df0a8)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/547ff5da-ec25-44a2-a0e3-2a2d5be2110e)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/73088bba-45af-45fc-b45f-515cce3ec6b3)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/2cdca4da-b05b-4a9a-87c3-de7c286a7a50)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/06c98ed9-880e-4317-b81c-0056f0c4fd71)
![Screenshot from 2023-05-10 11-58-54](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/92c26612-539f-46ed-9e26-9a7c174dc758)

## 二、camera内参

![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/1f9a0fcc-5f7d-4135-8cbb-5ae58d7fd37d)
![Screenshot from 2023-05-12 09-55-31](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/13c5030d-3897-4178-bbe2-e1452219af4b)

![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/6ff47a37-a680-42db-a9ce-0fcb1f031af0)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/9486b7ce-e2cd-4fc3-8cd2-3e28db2075ee)
![Screenshot from 2023-05-12 10-33-44](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/bf381187-44df-4909-bc2c-dfc5842e4d9e)

## 三、LiDAR-camera标定
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/e71acaad-bbf9-4969-bc3d-d0597f5c0fcb)
![Screenshot from 2023-05-12 10-40-16](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/4f79125f-766b-438b-a3af-a0ea2bb52282)

![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/4e8ce835-836e-41dd-9828-116963574633)
![Screenshot from 2023-05-12 10-41-13](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/dc5563f7-2196-49db-b8ef-ea7dafa88ac2)

![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/24dfd678-1d58-49db-82e6-cf049429ae34)
![Screenshot from 2023-05-12 12-09-53](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/237e5f35-59b3-4954-b3cd-6684090df5d3)

![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/2f380263-c0b6-4d63-b48a-682a632c9268)
![Screenshot from 2023-05-12 12-07-29](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/54c66ecc-31fc-4ccc-a442-de3624eaf3d5)

## 四、IMU标定
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/cf81ee89-e814-41d6-90aa-80b5c28d55b7)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/75ec6ee9-95ca-45c1-ad71-5cd4dc7621bc)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/06295c18-53cb-4999-8459-1500b67d0965)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/00961578-6cfa-4be7-85b1-7d5dc6eb6108)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/67b9932b-9089-4e55-a83d-2a210f18620e)
![Screenshot from 2023-05-12 14-01-12](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/12e3f384-949b-43d7-b1a4-61f16b1ea028)

## 五、LiDAR-IMU标定
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/db8fb1f2-22ef-487a-add1-b7b79d81eeef)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/cd5307fc-1b33-4fa3-bd4e-eb4d449de283)
![Screenshot from 2023-05-12 15-24-28](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/d240e529-4e41-49ec-9e76-082439014767)
![图片](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/faabbd8e-d5a2-419b-af85-c3270f44f665)
![Screenshot from 2023-05-12 15-29-32](https://github.com/pixmoving-moveit/pixkit-documentation-cn/assets/61351119/0dbc16a6-7af3-4584-8393-e9fc20544123)

**Comment by WuLyon** [comment]
@ahuazuipiaoliang

**Comment by zymouse** [comment]
感谢立洋的纠正，已经全部按照提示解决
